### ISSUE TITLE
Testsen känns inte helt 100

### ISSUE THREAD

**Issue by RichardDOMAS** [RichardDOMAS/datavetenskap#4]
När jag läser igenom vad vi ska testa ska VI bestämma vad vi ska testa.
Nu lämnar vi det lite upp till användaren. Kan vi göra på något annat sätt?

**Comment by k8vwsyz** [comment]
Hittade [här](https://stackoverflow.com/questions/20331209/haskell-unit-testing#20331512) om testing i haskell. Tror inte vi behöver ett helt projekt för den här inlämningen. Så sättet vi testar tror jag är okej.

**Comment by RichardDOMAS** [comment]
Haha, nej. Sättet vi testar är nog okej. Det jag funderar på är om vi på något sätt ska ha specifika nummer som vi testar. Frågan blir då vad fan inputten i funktionen ska vara, för man behöver en input i varje funktion i haskell va?

**Comment by k8vwsyz** [comment]
Vi kan byta ut max från en `Integer` till en lista av värderna vi vill testa typ.
```haskell
testFunction :: (Integer -> Integer -> Bool) -> [Integer]-> [Bool]
testFunction f testCases=
  foldl (\x y -> (f y y):x) [] testCases
```

**Comment by RichardDOMAS** [comment]
Hmm, det låter som en bra idé!

**Comment by k8vwsyz** [comment]
ska vi byta namn på f, x och y till lite bättre namn som förklarar vad dom är?

**Comment by RichardDOMAS** [comment]
Ja, allt som förtydligar är bra!
