### ISSUE TITLE
radlängd

### ISSUE THREAD

**Issue by k8vwsyz** [RichardDOMAS/datavetenskap#8]
![image](https://user-images.githubusercontent.com/42894294/45254313-97420800-b376-11e8-8087-2adfd6b15363.png)
> Does not have long lines (< 78 characters) or tab characters

ska vi fixa radlängderna innan vi skickar in eller ska vi lämna det som det är nu?

**Comment by RichardDOMAS** [comment]
Aha, det borde vi göra :) vi borde föröska fixa så det är så bra som möjligt.

**Comment by Askiary** [comment]
is fix, give donut
